//! Parser for scenarios.json metadata files.
//!
//! The scenarios.json file is generated by the Python pytest-tracer package
//! and contains metadata about all scenario tests in a project.

use std::fs;
use std::path::Path;

use serde::Deserialize;

use crate::error::ScenarioError;
use crate::models::Scenario;

/// The supported version of the scenarios file format.
const SUPPORTED_VERSION: &str = "1.0";

/// Raw scenarios file structure matching the JSON format.
#[derive(Debug, Deserialize)]
struct ScenariosFile {
    version: String,
    #[allow(dead_code)]
    collected_at: String,
    scenarios: Vec<Scenario>,
}

/// Parser for scenario metadata files.
pub struct ScenarioParser;

impl ScenarioParser {
    /// Parse a scenarios.json file and return the list of scenarios.
    pub fn parse(path: &Path) -> Result<Vec<Scenario>, ScenarioError> {
        if !path.exists() {
            return Err(ScenarioError::NotFound {
                path: path.display().to_string(),
            });
        }

        let content = fs::read_to_string(path)?;
        Self::parse_str(&content)
    }

    /// Parse scenarios from a JSON string.
    pub fn parse_str(content: &str) -> Result<Vec<Scenario>, ScenarioError> {
        let file: ScenariosFile = serde_json::from_str(content)?;

        if file.version != SUPPORTED_VERSION {
            return Err(ScenarioError::UnsupportedVersion {
                version: file.version,
            });
        }

        Ok(file.scenarios)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::ScenarioOutcome;

    #[test]
    fn test_parse_minimal_scenario() {
        let json = r#"{
            "version": "1.0",
            "collected_at": "2025-01-01T00:00:00",
            "scenarios": [
                {
                    "id": "tests/test_foo.py::test_bar",
                    "file": "tests/test_foo.py",
                    "function": "test_bar",
                    "description": "Test description"
                }
            ]
        }"#;

        let scenarios = ScenarioParser::parse_str(json).unwrap();
        assert_eq!(scenarios.len(), 1);

        let s = &scenarios[0];
        assert_eq!(s.id, "tests/test_foo.py::test_bar");
        assert_eq!(s.file, "tests/test_foo.py");
        assert_eq!(s.function, "test_bar");
        assert_eq!(s.description, "Test description");
        assert_eq!(s.documentation, None);
        assert!(s.behaviors.is_empty());
        assert_eq!(s.outcome, ScenarioOutcome::Success);
    }

    #[test]
    fn test_parse_full_scenario() {
        let json = r#"{
            "version": "1.0",
            "collected_at": "2025-01-01T00:00:00",
            "scenarios": [
                {
                    "id": "tests/test_auth.py::test_login",
                    "file": "tests/test_auth.py",
                    "function": "test_login",
                    "description": "User logs in successfully",
                    "documentation": "User logs in successfully\n\nGIVEN valid credentials\nWHEN user submits login\nTHEN they are authenticated",
                    "behaviors": ["authentication", "session"],
                    "outcome": "success"
                }
            ]
        }"#;

        let scenarios = ScenarioParser::parse_str(json).unwrap();
        assert_eq!(scenarios.len(), 1);

        let s = &scenarios[0];
        assert_eq!(s.description, "User logs in successfully");
        assert!(s.documentation.as_ref().unwrap().contains("GIVEN"));
        assert_eq!(s.behaviors, vec!["authentication", "session"]);
        assert_eq!(s.outcome, ScenarioOutcome::Success);
    }

    #[test]
    fn test_parse_error_scenario() {
        let json = r#"{
            "version": "1.0",
            "collected_at": "2025-01-01T00:00:00",
            "scenarios": [
                {
                    "id": "tests/test_auth.py::test_login_fails",
                    "file": "tests/test_auth.py",
                    "function": "test_login_fails",
                    "description": "Login fails with bad password",
                    "behaviors": ["authentication"],
                    "outcome": "error"
                }
            ]
        }"#;

        let scenarios = ScenarioParser::parse_str(json).unwrap();
        assert_eq!(scenarios[0].outcome, ScenarioOutcome::Error);
    }

    #[test]
    fn test_parse_multiple_scenarios() {
        let json = r#"{
            "version": "1.0",
            "collected_at": "2025-01-01T00:00:00",
            "scenarios": [
                {
                    "id": "tests/test_a.py::test_one",
                    "file": "tests/test_a.py",
                    "function": "test_one",
                    "description": "First test"
                },
                {
                    "id": "tests/test_a.py::test_two",
                    "file": "tests/test_a.py",
                    "function": "test_two",
                    "description": "Second test"
                }
            ]
        }"#;

        let scenarios = ScenarioParser::parse_str(json).unwrap();
        assert_eq!(scenarios.len(), 2);
        assert_eq!(scenarios[0].function, "test_one");
        assert_eq!(scenarios[1].function, "test_two");
    }

    #[test]
    fn test_parse_unsupported_version() {
        let json = r#"{
            "version": "2.0",
            "collected_at": "2025-01-01T00:00:00",
            "scenarios": []
        }"#;

        let result = ScenarioParser::parse_str(json);
        assert!(matches!(
            result,
            Err(ScenarioError::UnsupportedVersion { version }) if version == "2.0"
        ));
    }

    #[test]
    fn test_parse_invalid_json() {
        let json = "not valid json";
        let result = ScenarioParser::parse_str(json);
        assert!(matches!(result, Err(ScenarioError::ParseError(_))));
    }

    #[test]
    fn test_parse_empty_scenarios() {
        let json = r#"{
            "version": "1.0",
            "collected_at": "2025-01-01T00:00:00",
            "scenarios": []
        }"#;

        let scenarios = ScenarioParser::parse_str(json).unwrap();
        assert!(scenarios.is_empty());
    }
}
